version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.1.0
    container_name: '${APP_SLUG}-mysql'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - ./.docker/mysql/entry:/docker-entrypoint-initdb.d

  redis-primary:
    image: redis:latest
    container_name: '${APP_SLUG}-redis-primary'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./.docker/redis/redis.conf:/etc/redis/redis.conf
      - ${REDIS_DATA_PATH}:/var/lib/redis
    networks:
      - redis-replication
    ports:
      - '${REDIS_PRIMARY_PORT}:6379'

  redis-slave:
    image: redis:latest
    container_name: '${APP_SLUG}-redis-replica'
    ports:
      - '${REDIS_REPLICA_PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD} --replicaof ${APP_SLUG}-redis-primary ${REDIS_PRIMARY_PORT}
    depends_on:
      - redis-primary
    volumes:
      - ./.docker/redis/replica/redis.conf:/etc/redis/redis.conf
    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge